// apps/studio/src/app/app.tsx
import { Header } from './components/Header';
import { createBrowserRouter, Outlet, RouterProvider } from 'react-router-dom';

import { HomePage } from './pages/Home';

const router = createBrowserRouter([
  {
    element: (
      <>
        <Header />
        <main className="flex flex-col items-center justify-center pt-16">
          <Outlet />
        </main>
      </>
    ),
    children: [{ path: '/', element: <HomePage /> }],
  },
]);

export function App() {
  return <RouterProvider router={router} />;
}

export default App;

// studio/src/app/app.component.ts
import {Component} from '@angular/core';
import {RouterModule} from '@angular/router';
import {HeaderComponent} from "./core/components/header.component";

@Component({
  standalone: true,
  imports: [RouterModule, HeaderComponent],
  selector: 'beever-root',
  template: `
      <beever-header></beever-header>
      <main class="flex flex-col items-center justify-center pt-16">
          <router-outlet></router-outlet>
      </main>
  `,
})
export class AppComponent {
}

<beever-header></beever-header>
<router-outlet></router-outlet>
